### ISSUE TITLE
red5 1.0.6 exception

### ISSUE THREAD

**Issue by sayHellowWord** [Red5/red5-server#179]
when run the red5 1.0.6 server, has throws exception"
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchr
        at java.util.concurrent.Semaphore.tryAcquire(Semaphore.java:414) ~[na:1.7.0_67]
        at org.red5.server.net.rtmp.RTMPMinaConnection.write(RTMPMinaConnection.java:324) ~[red5-server-com
        at org.red5.server.net.rtmp.Channel.write(Channel.java:136) [red5-server-common-1.0.6-RELEASE.jar:1
        at org.red5.server.net.rtmp.Channel.write(Channel.java:106) [red5-server-common-1.0.6-RELEASE.jar:1
        at org.red5.server.net.rtmp.RTMPHandler.onCommand(RTMPHandler.java:486) [red5-server-common-1.0.6-R
        at org.red5.server.net.rtmp.BaseRTMPHandler.messageReceived(BaseRTMPHandler.java:105) [red5-server-
        at org.red5.server.net.rtmp.ReceivedMessageTask.call(ReceivedMessageTask.java:63) [red5-server-comm
        at org.red5.server.net.rtmp.ReceivedMessageTask.call(ReceivedMessageTask.java:14) [red5-server-comm
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_67]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
![image](https://cloud.githubusercontent.com/assets/11717083/15201598/4b6a2032-1825-11e6-9700-110a67a6dc14.png)

**Comment by virgilbugnariu** [comment]
Are you running it as administrator?

**Comment by mondain** [comment]
Re-try this with 1.0.7 release and print the stacktrace if it occurs.
