### ISSUE TITLE
help,why not find  items for ofla_demo（red5 application intaller）？

### ISSUE THREAD

**Issue by fmpoffice** [Red5/red5-server#180]
why not find  items for ofla_demo（red5 application intaller）？

![2](https://cloud.githubusercontent.com/assets/11001031/15382059/66766a64-1db8-11e6-9efc-cfc209e23185.png)
![1](https://cloud.githubusercontent.com/assets/11001031/15382060/6ec67cae-1db8-11e6-8c59-f561abc118ea.png)
![3](https://cloud.githubusercontent.com/assets/11001031/15382089/ce3051ec-1db8-11e6-9976-fde52c18e543.png)

**Comment by mondain** [comment]
The url being used by the installer used to point at googlecode, that may not work anymore; I'll check into it.

**Comment by fmpoffice** [comment]
Cannot access googlecode in China, the problem has been solved, oflaDemo directly download from other friends, set up the test is successful, thank you!

**Comment by ErickAsmock** [comment]
Seems persistent and related to the googlecode.


2016-05-22 12:29:58,628 [NioProcessor-7] INFO  o.r.s.adapter.ApplicationAdapter - W3C x-category:session x-event:disconnect c-ip:0:0:0:0:0:0:0:1 c-client-id:1
2016-05-22 12:29:59,205 [RTMPConnectionExecutor-1] INFO  o.r.s.adapter.ApplicationAdapter - W3C x-category:session x-event:connect c-ip:0:0:0:0:0:0:0:1 c-client-id:2
2016-05-22 12:30:15,879 [NioProcessor-8] INFO  o.r.s.adapter.ApplicationAdapter - W3C x-category:session x-event:disconnect c-ip:0:0:0:0:0:0:0:1 c-client-id:2
2016-05-22 12:30:19,277 [RTMPConnectionExecutor-1] INFO  o.r.s.adapter.ApplicationAdapter - W3C x-category:session x-event:connect c-ip:0:0:0:0:0:0:0:1 c-client-id:3
2016-05-22 12:30:21,291 [DeadlockGuardScheduler-6] WARN  o.r.s.n.r.ReceivedMessageTaskQueue - Interrupting unfinished active task [sessionId: ZYWTHQEYUCYXS; packetNumber: 2; processing: true]
2016-05-22 12:30:21,299 [RTMPConnectionExecutor-1] ERROR org.red5.server.service.Installer - Unable to connect to http://red5.googlecode.com/svn/snapshots/
org.apache.http.impl.execchain.RequestAbortedException: Request aborted
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:193)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)

**Comment by TheJamesKing** [comment]
Is there a different URL we can in the config?

**Comment by mondain** [comment]
I've found and copied some of the old installer files to a new location, to use them, change your `webapps/installer/WEB-INF/red5-web.properties` file. Change the `application.repository.url` parameter from:
```
application.repository.url=http://red5.googlecode.com/svn/snapshots/
```
to
```
application.repository.url=http://red5.org/snapshots/
```

**Comment by romanown** [comment]
When i go Install in the box writing 
Trying to connect to war location
Net status: NetConnection.Connect.Failed

**Comment by romanown** [comment]
application.repository.url=http://red5.org/snapshots/ on red5 an windows 7 do not working.
Trying to connect to war location
Net status: NetConnection.Connect.Failed

**Comment by mondain** [comment]
You're getting `NetConnection.Connect.Failed` because your server isn't running or you dont have the installer app

**Comment by durgeshmandal** [comment]
My red5 server is running but where I use videos whisper wordpress plugin it show Net status: NetConnection.Connect.Failed while all demo are working fine

**Comment by mondain** [comment]
I've got no experience with videowishper; you'll have to ask their maintainers.

**Comment by durgeshmandal** [comment]
When I am starting red5 server I am getting this message "org.red5.server.service.ShutdownServer - One or more contexts didn't close in the allotted time" and I never get red5 sucess message can you tell me what will be message when red5 will be started and execute all process although I am able to connect and see demo app by browser
