### ISSUE TITLE
[ERROR] [RTMPConnectionExecutor-3] org.red5.server.service.ServiceInvoker - Error executing call: Service: null Method: publish Num Params: 1 0: null

### ISSUE THREAD

**Issue by hezila** [Red5/red5-server#211]
# Issue

### Short description

Sometimes, the live audio stream cannot be pushed. The following is the error log:

```
[ERROR] [RTMPConnectionExecutor-3] org.red5.server.service.ServiceInvoker - Error executing call: Service: null Method: publish Num Params: 1 0: null
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.red5.server.service.ServiceInvoker.invoke(ServiceInvoker.java:189)
        at org.red5.server.net.rtmp.RTMPHandler.invokeCall(RTMPHandler.java:214)
        at org.red5.server.net.rtmp.RTMPHandler.onCommand(RTMPHandler.java:276)
        at org.red5.server.net.rtmp.BaseRTMPHandler.messageReceived(BaseRTMPHandler.java:116)
        at org.red5.server.net.rtmp.ReceivedMessageTask.call(ReceivedMessageTask.java:72)
        at org.red5.server.net.rtmp.ReceivedMessageTask.call(ReceivedMessageTask.java:38)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
        at org.red5.server.stream.StreamService.publish(StreamService.java:599)
        ... 15 common frames omitted
```

### Environment

[] Operating system and version: Ubuntu 14.04.5 LTS
[] Java version: "1.8.0_111"
[] Red5 version: "red5-server-1.0.8-M13"

**Comment by mondain** [comment]
Publish is somehow being called with a null param, not sure how that would happen and without more info on the call being made, I'm not sure I can go further. The NPE hit on the second line below 
```
    public void publish(Boolean dontStop) {
        if (!dontStop) {
```

**Comment by mondain** [comment]
Next push allows `null` as `false`
