### ISSUE TITLE
Red5 > 1.0.8 doesn't work with tomcat webscokets

### ISSUE THREAD

**Issue by Dima00782** [Red5/red5-server#227]
# Issue
WS from tomcat embed hasn't working since 1.08*

### Short description
I'm using tomcat websocket with red5 1.07-RELEASE and all were ok.
In red5-1.08 and higher they suddenly stopped work.

### Environment

[] Operating system and version: Ubuntu 16.04 LTS
[] Java version: 1.8.0_121, hotspot
[] Red5 version: 1.08 and higher

### Expected behavior
I'm using tomcat embed ws in red5 1.07-RELESE and everything is fine.
I expect that tomcat WS should work in red5-1.08 but unfortunately it isn't so.

### Actual behavior
red5-1.08* and higher version fail with concurrent timeout exception on any WS send operation.

### Steps to reproduce
You can use this trivial project for reproducing the problem.
https://github.com/Dima00782/signalling_server

Or just use any tomcat ws example and try to send message from WS server.
e.g. session.getBasicRemote().sendText("something");

### Logs
[ERROR] [http-nio-0.0.0.0-5080-exec-3] org.red5.signalling.SignalConnection - Error java.io.IOException: java.util.concurrent.TimeoutException
java.io.IOException: java.util.concurrent.TimeoutException
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.handleSendFailureWithEncode(WsRemoteEndpointImplBase.java:558) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.handleSendFailure(WsRemoteEndpointImplBase.java:533) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:285) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsSession.sendCloseMessage(WsSession.java:587) ~[tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsSession.doClose(WsSession.java:489) ~[tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.handleSendFailureWithEncode(WsRemoteEndpointImplBase.java:548) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.handleSendFailure(WsRemoteEndpointImplBase.java:533) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:260) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:195) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.red5.signalling.SignalConnection.onOpen(SignalConnection.java:95) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.apache.tomcat.websocket.pojo.PojoEndpointBase.doOnOpen(PojoEndpointBase.java:66) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.pojo.PojoEndpointServer.onOpen(PojoEndpointServer.java:70) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:128) [tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:848) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1441) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.12.jar:8.5.12]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.util.concurrent.TimeoutException: null
	at org.apache.tomcat.websocket.FutureToSendHandler.get(FutureToSendHandler.java:111) ~[tomcat-websocket-8.0.33.jar:8.0.33]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessageBlock(WsRemoteEndpointImplBase.java:278) [tomcat-websocket-8.0.33.jar:8.0.33]
	... 22 common frames omitted

**Comment by solomax** [comment]
I'm afraid such short description with no details make no sense
By default red5, have no tomcat websockets bundled ....

**Comment by Dima00782** [comment]
I've completed description, hope this help to fix this issue.
