### ISSUE TITLE
integrate red5 (red5-server-1.0.9-RELEASE) and Tomcat (tomcat8)

### ISSUE THREAD

**Issue by RivsDC** [Red5/red5-server#233]
# integrate red5 (red5-server-1.0.9-RELEASE) and Tomcat (tomcat8)

### Short description
When I integrate red5 (red5-server-1.0.9-RELEASE) and Tomcat (tomcat8), I copy the configuration file, and the following questions arise.
`[WARN] [localhost-startStop-1] org.springframework.context.support.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'default.context' defined in URL [file:/F:/apache-tomcat-8.0.45/webapps/red5/WEB-INF/classes/beanRefContext.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.red5.server.Context@586d7ec1] with key 'global.context'; nested exception is javax.management.NotCompliantMBeanException: org.red5.server.jmx.mxbeans.ContextMXBean: Method org.red5.server.jmx.mxbeans.ContextMXBean.getResource has parameter or return type that cannot be translated into an open type
[ERROR] [localhost-startStop-1] org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.access.BootstrapException: Unable to initialize group definition. Group resource name [classpath*:beanRefContext.xml], factory key [default.context]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'default.context' defined in URL [file:/F:/apache-tomcat-8.0.45/webapps/red5/WEB-INF/classes/beanRefContext.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.red5.server.Context@586d7ec1] with key 'global.context'; nested exception is javax.management.NotCompliantMBeanException: org.red5.server.jmx.mxbeans.ContextMXBean: Method org.red5.server.jmx.mxbeans.ContextMXBean.getResource has parameter or return type that cannot be translated into an open type
	at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:388)
	at org.springframework.web.context.ContextLoader.loadParentContext(ContextLoader.java:563)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:322)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.red5.server.war.WarLoaderServlet.contextInitialized(WarLoaderServlet.java:113)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`
### Environment

[] Operating system and version:tomcat8
[] Java version:jdk8
[] Red5 version:red5-server-1.0.9-RELEASE

### Expected behavior
__Put as much detail here as possible__
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'default.context' defined in URL [file:/F:/apache-tomcat-8.0.45/webapps/red5/WEB-INF/classes/beanRefContext.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.red5.server.Context@586d7ec1] with key 'global.context'; nested exception is javax.management.NotCompliantMBeanException: org.red5.server.jmx.mxbeans.ContextMXBean: Method org.red5.server.jmx.mxbeans.ContextMXBean.getResource has parameter or return type that cannot be translated into an open type
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.access.ContextSingletonBeanFactoryLocator.initializeDefinition(ContextSingletonBeanFactoryLocator.java:143)
	at org.springframework.beans.factory.access.SingletonBeanFactoryLocator.useBeanFactory(SingletonBeanFactoryLocator.java:383)
	... 13 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.support.ClassPathXmlApplicationContext]: Constructor threw exception; nested exception is org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.red5.server.Context@586d7ec1] with key 'global.context'; nested exception is javax.management.NotCompliantMBeanException: org.red5.server.jmx.mxbeans.ContextMXBean: Method org.red5.server.jmx.mxbeans.ContextMXBean.getResource has parameter or return type that cannot be translated into an open type
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	... 26 common frames omitted
Caused by: org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.red5.server.Context@586d7ec1] with key 'global.context'; nested exception is javax.management.NotCompliantMBeanException: org.red5.server.jmx.mxbeans.ContextMXBean: Method org.red5.server.jmx.mxbeans.ContextMXBean.getResource has parameter or return type that cannot be translated into an open type
	at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:628)
	at org.springframework.jmx.export.MBeanExporter.registerBeans(MBeanExporter.java:550)
	at org.springframework.jmx.export.MBeanExporter.afterSingletonsInstantiated(MBeanExporter.java:432)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 28 common frames omitted
Caused by: javax.management.NotCompliantMBeanException: org.red5.server.jmx.mxbeans.ContextMXBean: Method org.red5.server.jmx.mxbeans.ContextMXBean.getResource has parameter or return type that cannot be translated into an open type
	at com.sun.jmx.mbeanserver.Introspector.throwException(Introspector.java:466)
	at com.sun.jmx.mbeanserver.MBeanAnalyzer.<init>(MBeanAnalyzer.java:120)
	at com.sun.jmx.mbeanserver.MBeanAnalyzer.analyzer(MBeanAnalyzer.java:102)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getAnalyzer(MXBeanIntrospector.java:74)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getPerInterface(MBeanIntrospector.java:192)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:138)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:202)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.springframework.jmx.support.MBeanRegistrationSupport.doRegister(MBeanRegistrationSupport.java:195)
	at org.springframework.jmx.export.MBeanExporter.registerBeanInstance(MBeanExporter.java:674)
	at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:618)
	... 40 common frames omitted
Caused by: java.lang.IllegalArgumentException: Method org.red5.server.jmx.mxbeans.ContextMXBean.getResource has parameter or return type that cannot be translated into an open type
	at com.sun.jmx.mbeanserver.ConvertingMethod.from(ConvertingMethod.java:46)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.mFrom(MXBeanIntrospector.java:84)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.mFrom(MXBeanIntrospector.java:54)
	at com.sun.jmx.mbeanserver.MBeanAnalyzer.initMaps(MBeanAnalyzer.java:137)
	at com.sun.jmx.mbeanserver.MBeanAnalyzer.<init>(MBeanAnalyzer.java:118)
	... 52 common frames omitted`

### Logs
https://stackoverflow.com/questions/45502816/integrate-red5-red5-server-1-0-9-release-and-tomcat-tomcat8

**Comment by mondain** [comment]
Red5 has been integrated with Tomcat 8 and actually 8.5 for awhile now; I'm not sure exactly what you're trying to accomplish.

**Comment by qickrooms** [comment]
I think RivsDC was trying to install red5 into a baseline tomcat 8.x directory without building/copying the server first. I have added an response on stack exchange.

https://stackoverflow.com/questions/45502816/integrate-red5-red5-server-1-0-9-release-and-tomcat-tomcat8/49819204#49819204
