### ISSUE TITLE
java.lang.OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by canwin123** [Red5/red5-server#248]
I put a mp4 of 400M at \webapps\oflaDemo\streams,and when I played it at index.html,the server occured error and logged like this:
 java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Unknown Source)
        at java.nio.DirectByteBuffer.<init>(Unknown Source)
        at java.nio.ByteBuffer.allocateDirect(Unknown Source)
        at org.mp4parser.support.AbstractBox.parse(AbstractBox.java:95)
        at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:107)
        at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
        at org.mp4parser.IsoFile.<init>(IsoFile.java:55)
        at org.mp4parser.IsoFile.<init>(IsoFile.java:50)
        at org.red5.io.mp4.impl.MP4Reader.<init>(MP4Reader.java:272)
        at org.red5.io.mp4.impl.MP4.getReader(MP4.java:145)
        at org.red5.server.stream.provider.FileProvider.init(FileProvider.java:240)
        at org.red5.server.stream.provider.FileProvider.pullMessage(FileProvider.java:134)
        at org.red5.server.messaging.InMemoryPullPullPipe.pullMessage(InMemoryPullPullPipe.java:67)
        at org.red5.server.stream.PlayEngine$PullAndPushRunnable.execute(PlayEngine.java:1921)
        at org.red5.server.scheduling.QuartzSchedulingServiceJob.executeInternal(QuartzSchedulingServiceJob.java:89)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

I will appreciate it if someone could help me.

### Environment

Operating system and version:win10
Java version:1.8.0_144
Red5 version:red5-server-1.0.9-RELEASE

**Comment by mondain** [comment]
I would assume that the dependency mp4parser was not able to allocate enough RAM to parse the given MP4 file.

**Comment by kidovin** [comment]
how to solve it?

**Comment by mondain** [comment]
Change the mp4 to fast-load so the configuration is at the beginning of the file or use smaller mp4 files.
